language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: KA3o3Ju/2JBh8cEcfHr+V8GmPe4s393k2wtdCLSfqoi1g2VuMiAKF/3kEPu7eVpJNOB4QHgGTfiSSSMMHtsViPFdWNmJBBjtu8Liya7THdpdfrjzKZtKmGQkxiuJfLesuItrUSqrLT/dJBoeirRS4nY2hJEani8ZIX+MB5HaGP+bkbY3fl7ad5cP/lm13Wjj5ssFvSnsbnqJ0lQXuHiHwjSsfnL8d3LRMBasOyZzud70DgUg4hMZVmzLXk2mPCPzJvYd7ZguhvMjaVPaPZpE7tvHbASIara3BKzKVUvkKbb3dGK7J2W5zp5SCus9oUzGKYG7MATiGN1IpPuhj7ju6qpMj708fggWaWwqS46EYul/akiQ5Z8mmMJcsJPzla5kJuT95usP3uhdVnUo9mbPz3+Yp58P6gwIPuwq/FzsfHVX5jmH01kzaPikhcqVngTSd7lHpplkT07n7BzY/m+vYJn+fYvdqqMOlkoG0jKDrnL5Iv82AY30Nah0J31DvYU/LaOEY9AqHl1totB8NfyqUG1PvVFaBgEUBGzoZgXlke+TeWiQHikOfjyC5oyi34BejfKGhbZQ+EmfKf1Ws7MOhaVEgo+uP5GSMSgdyfU3As+vBjSwq7vgNnee1AiaKVwRpFfRKp9KUWdFzSBzCj6iCBBLLTc52SLYsXcl2WxEk8o=
  app: secure-dusk-74453
  on:
    repo: jhoglen1/Community
